version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    cpuset: "1"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: checkloud-db.ccsihrpn6zox.ap-northeast-2.rds.amazonaws.com
            database: checkloud-db
            schema: public
            user: jngcii
            password: 'asdf1488?!'
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: true